// ============================================================
//  src/lib/mockData.js
//  Fallback data used when Supabase is not configured
// ============================================================

// ─── Demo Users (for quick login during testing) ─────────
export const DEMO_USERS = [
  {
    id: 'user_001',
    email: 'aryan@demo.colab',
    password: 'demo1234',
    full_name: 'Aryan Mehta',
    skills: ['React', 'Node.js', 'Python', 'OpenAI'],
    college: 'IIT Bombay',
    avatar: 'AM',
    role: 'Full-Stack Developer',
  },
  {
    id: 'user_002',
    email: 'priya@demo.colab',
    password: 'demo1234',
    full_name: 'Priya Sharma',
    skills: ['React Native', 'ARKit', 'Node.js', 'Figma'],
    college: 'BITS Pilani',
    avatar: 'PS',
    role: 'Mobile / AR Developer',
  },
  {
    id: 'user_003',
    email: 'rohan@demo.colab',
    password: 'demo1234',
    full_name: 'Rohan Verma',
    skills: ['Solidity', 'Web3', 'React', 'IPFS'],
    college: 'NIT Trichy',
    avatar: 'RV',
    role: 'Blockchain Developer',
  },
  {
    id: 'user_004',
    email: 'sneha@demo.colab',
    password: 'demo1234',
    full_name: 'Sneha Patil',
    skills: ['Python', 'TensorFlow', 'FastAPI', 'GIS'],
    college: 'COEP Pune',
    avatar: 'SP',
    role: 'ML / Data Scientist',
  },
];

// ─── Mock Projects ────────────────────────────────────────
export const MOCK_PROJECTS = [
  {
    id: '1',
    title: 'AI-Powered Study Buddy',
    description: 'Build an LLM-based tool that generates personalised study plans from syllabus PDFs. We need a full-stack team with AI/ML and frontend expertise.',
    domain: 'Startup',
    skills_list: ['Python', 'LangChain', 'React', 'OpenAI'],
    owner_name: 'Aryan Mehta',
    owner_id: 'user_001',
    status: 'open',
    interest_count: 7,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: '2',
    title: 'Smart Campus Navigator',
    description: 'AR overlay on mobile that guides students across the campus in real-time using indoor positioning and computer vision.',
    domain: 'Hackathon',
    skills_list: ['React Native', 'ARKit', 'Node.js', 'Maps API'],
    owner_name: 'Priya Sharma',
    owner_id: 'user_002',
    status: 'open',
    interest_count: 12,
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: '3',
    title: 'Blockchain Credential Vault',
    description: 'Decentralised system for verifying and sharing academic credentials via NFT-backed certificates stored on IPFS.',
    domain: 'Research',
    skills_list: ['Solidity', 'Ethereum', 'IPFS', 'React'],
    owner_name: 'Rohan Verma',
    owner_id: 'user_003',
    status: 'open',
    interest_count: 4,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: '4',
    title: 'Agri-Tech Yield Predictor',
    description: 'ML model that predicts crop yield based on soil and weather data for local farmers in rural Maharashtra.',
    domain: 'Research',
    skills_list: ['Python', 'TensorFlow', 'FastAPI', 'GIS'],
    owner_name: 'Sneha Patil',
    owner_id: 'user_004',
    status: 'open',
    interest_count: 9,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: '5',
    title: 'EcoTrack — Campus Carbon Monitor',
    description: 'Interactive dashboard that monitors and gamifies the carbon footprint of college departments. Uses IoT sensor data.',
    domain: 'Startup',
    skills_list: ['React', 'D3.js', 'Node.js', 'PostgreSQL'],
    owner_name: 'Kabir Das',
    owner_id: 'user_005',
    status: 'open',
    interest_count: 6,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: '6',
    title: 'HackBoard — Live Hackathon Platform',
    description: 'Real-time platform for managing teams, submissions and judging during inter-college hackathons with live leaderboard.',
    domain: 'Hackathon',
    skills_list: ['React', 'Socket.io', 'Express', 'Redis'],
    owner_name: 'Anika Singh',
    owner_id: 'user_006',
    status: 'filled',
    interest_count: 15,
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: '7',
    title: 'MediScan — Diagnostic AI Assistant',
    description: 'Deep learning model that analyses chest X-rays and MRI scans to flag potential anomalies, helping doctors in resource-limited clinics.',
    domain: 'Research',
    skills_list: ['Python', 'PyTorch', 'OpenCV', 'Flask'],
    owner_name: 'Dev Kapoor',
    owner_id: 'user_007',
    status: 'open',
    interest_count: 11,
    created_at: new Date(Date.now() - 86400000 * 1.5).toISOString(),
  },
  {
    id: '8',
    title: 'SkillSwap — Peer-to-Peer Learning',
    description: 'Marketplace where students trade skills — you teach Python, someone else teaches Figma. Smart matching via embedding similarity.',
    domain: 'Startup',
    skills_list: ['React', 'Node.js', 'PostgreSQL', 'OpenAI'],
    owner_name: 'Tanya Rao',
    owner_id: 'user_008',
    status: 'open',
    interest_count: 19,
    created_at: new Date(Date.now() - 86400000 * 0.5).toISOString(),
  },
  {
    id: '9',
    title: 'InfraWatch — Smart City Dashboard',
    description: '24-hour hackathon project: real-time dashboard ingesting municipal IoT sensor feeds (traffic, water, power) with anomaly alerts.',
    domain: 'Hackathon',
    skills_list: ['React', 'MQTT', 'InfluxDB', 'Grafana'],
    owner_name: 'Ravi Nair',
    owner_id: 'user_009',
    status: 'open',
    interest_count: 8,
    created_at: new Date(Date.now() - 86400000 * 0.8).toISOString(),
  },
  {
    id: '10',
    title: 'CodeCollab — Real-time Pair Programming',
    description: 'Browser-based VS Code–like editor with real-time multi-cursor collaboration, video chat, and AI code review suggestions.',
    domain: 'Startup',
    skills_list: ['React', 'WebSockets', 'Monaco Editor', 'Node.js'],
    owner_name: 'Ishaan Bose',
    owner_id: 'user_010',
    status: 'open',
    interest_count: 22,
    created_at: new Date(Date.now() - 86400000 * 0.3).toISOString(),
  },
  {
    id: '11',
    title: 'SolarSim — Renewable Energy Modeller',
    description: 'Research tool that simulates optimal solar panel placement for Indian campuses using GIS data and weather APIs.',
    domain: 'Research',
    skills_list: ['Python', 'GIS', 'NumPy', 'FastAPI'],
    owner_name: 'Pooja Iyer',
    owner_id: 'user_011',
    status: 'open',
    interest_count: 5,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: '12',
    title: 'EventPulse — College Fest Manager',
    description: '36-hour hackathon build: end-to-end college event management — registrations, QR check-ins, live schedule, sponsor dashboards.',
    domain: 'Hackathon',
    skills_list: ['React', 'Node.js', 'QR Code', 'Tailwind'],
    owner_name: 'Mihir Shah',
    owner_id: 'user_012',
    status: 'open',
    interest_count: 14,
    created_at: new Date(Date.now() - 86400000 * 2.5).toISOString(),
  },
];

// ─── Hackathon Teams ─────────────────────────────────────
export const HACKATHON_TEAMS = [
  {
    id: 'team_001',
    name: 'ByteForce',
    hackathon: 'Smart India Hackathon 2025',
    project: 'Smart Campus Navigator',
    status: 'active',
    slots_total: 4,
    slots_filled: 3,
    members: [
      { name: 'Priya Sharma',  role: 'Team Lead / Mobile Dev', avatar: 'PS' },
      { name: 'Aryan Mehta',   role: 'Backend Developer',      avatar: 'AM' },
      { name: 'Dev Kapoor',    role: 'ML Engineer',            avatar: 'DK' },
    ],
    looking_for: ['React Native Developer'],
    tech_stack: ['React Native', 'Node.js', 'TensorFlow Lite', 'ARKit'],
  },
  {
    id: 'team_002',
    name: 'ChainGuard',
    hackathon: 'ETHIndia 2025',
    project: 'Blockchain Credential Vault',
    status: 'active',
    slots_total: 5,
    slots_filled: 4,
    members: [
      { name: 'Rohan Verma',   role: 'Smart Contract Dev',  avatar: 'RV' },
      { name: 'Sneha Patil',   role: 'Frontend Developer',  avatar: 'SP' },
      { name: 'Kabir Das',     role: 'Full-Stack',          avatar: 'KD' },
      { name: 'Tanya Rao',     role: 'UI/UX Designer',      avatar: 'TR' },
    ],
    looking_for: ['Solidity Expert'],
    tech_stack: ['Solidity', 'Hardhat', 'React', 'IPFS', 'Ethers.js'],
  },
  {
    id: 'team_003',
    name: 'GreenPulse',
    hackathon: 'NASA Space Apps 2025',
    project: 'SolarSim — Renewable Energy Modeller',
    status: 'forming',
    slots_total: 4,
    slots_filled: 2,
    members: [
      { name: 'Pooja Iyer',    role: 'Data Scientist',    avatar: 'PI' },
      { name: 'Ravi Nair',     role: 'Backend / APIs',    avatar: 'RN' },
    ],
    looking_for: ['GIS Specialist', 'Frontend Developer'],
    tech_stack: ['Python', 'QGIS', 'FastAPI', 'Leaflet.js'],
  },
  {
    id: 'team_004',
    name: 'NeuralNexus',
    hackathon: 'Microsoft Imagine Cup 2026',
    project: 'MediScan — Diagnostic AI Assistant',
    status: 'active',
    slots_total: 5,
    slots_filled: 5,
    members: [
      { name: 'Dev Kapoor',    role: 'ML Lead',           avatar: 'DK' },
      { name: 'Ishaan Bose',   role: 'Backend Developer', avatar: 'IB' },
      { name: 'Mihir Shah',    role: 'Frontend Dev',      avatar: 'MS' },
      { name: 'Anika Singh',   role: 'DevOps / Cloud',    avatar: 'AS' },
      { name: 'Pooja Iyer',    role: 'Research / Data',   avatar: 'PI' },
    ],
    looking_for: [],
    tech_stack: ['PyTorch', 'FastAPI', 'React', 'Docker', 'Azure'],
  },
];

// ─── Simulated logged-in user profile ────────────────────
export const USER_PROFILE = {
  id: 'current_user',
  name: 'You',
  skills: ['React', 'Node.js', 'Python', 'TensorFlow'],
};

// ─── Domain color map ─────────────────────────────────────
export const DOMAIN_COLORS = {
  Startup:   { bg: 'rgba(56,189,248,0.15)',  border: '#38bdf8', text: '#38bdf8'  },
  Hackathon: { bg: 'rgba(129,140,248,0.15)', border: '#818cf8', text: '#818cf8' },
  Research:  { bg: 'rgba(192,132,252,0.15)', border: '#c084fc', text: '#c084fc' },
};
